In [19]:
import numpy as np

In [20]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [21]:
a =[1,2,3,4,"Pankaj"]
a

[1, 2, 3, 4, 'Pankaj']

In [22]:
np.array(a)

array(['1', '2', '3', '4', 'Pankaj'], dtype='<U21')

## Vectors - 1D Array
## Matrices - 2D Array
## Tensors - 3D Array

In [23]:
l = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [24]:
np.array(1)

array(1)

## BOOLEAN INDEXING

In [25]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [26]:
boolean_index = arr % 2 == 0
boolean_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [27]:
arr = arr[boolean_index]
arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

## NUMPY - ARRAY OPERATIONS

- ARITHMETIC OPERATIONS

In [28]:
a1 = np.array([1,2,3,4,5,])
a2 = np.array([6,7,8,9,10])

In [29]:
a3 = a1 + a2
a3 

array([ 7,  9, 11, 13, 15])

In [30]:
a3 = a1 ** a2
a3

array([      1,     128,    6561,  262144, 9765625])

- BROADCASTING

In [32]:
l = [10,20,30,40]
arr = np.array(l)
arr

array([10, 20, 30, 40])

In [33]:
arr + 20

array([30, 40, 50, 60])

## DEEP AND SHALLOW COPY

In [34]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
slice = a [:6]
slice = slice * 10
slice

array([10, 20, 30, 40, 50, 60])

In [36]:
a #deep copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
b = a.copy()  #shallow copy
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [38]:
b[0]= 1000
b

array([1000,    2,    3,    4,    5,    6,    7,    8,    9,   10,   11,
         12,   13,   14,   15,   16,   17,   18,   19,   20])

## MATRIX OPERATIONS

In [39]:
A = np.array(([1,2],[4,5]))
B = np.array(([7,8],[9,10]))    

In [40]:
A

array([[1, 2],
       [4, 5]])

In [41]:
B

array([[ 7,  8],
       [ 9, 10]])

In [42]:
A * B

array([[ 7, 16],
       [36, 50]])

In [43]:
A @ B  # multiplication

array([[25, 28],
       [73, 82]])

- TRANSPOSE OF A MATRIX

In [44]:
A.T

array([[1, 4],
       [2, 5]])

## ADVANCE ARRAY MANUPLATIONS

In [45]:
A

array([[1, 2],
       [4, 5]])

In [46]:
B

array([[ 7,  8],
       [ 9, 10]])